services:
  - type: web
    name: praxisreportai
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: praxisreportdb
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Set manually via Render dashboard
      - key: SECRET_KEY
        sync: false  # Set manually via Render dashboard
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALGORITHM
        value: "HS256"

databases:
  - name: praxisreportdb
    plan: free
    databaseName: praxisreportdb
    user: praxisreportdb_user