services:
  - type: web
    name: praxisreportai
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        libpango-1.0-0 \
        libcairo2 \
        libgdk-pixbuf2.0-0 \
        libffi-dev \
        libjpeg-dev \
        libpng-dev \
        libxml2 \
        libxslt1.1 \
        libssl-dev \
        fonts-liberation \
        fonts-dejavu-core && \
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALGORITHM
        value: "HS256"